version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app/static
    depends_on:
      - project1
      - project2
  project1:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project1.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/static
    ports:
      - "8000:8000"
  project2:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project2.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/static
    ports:
      - "8000:8000"
volumes:
  static_data:


